Feat/#23 video to script
Tube-Slice/Tube-Slice-BE pull request #50
Opened 2024-05-08 10:56 UTC by KimChungEon

2024-05-08 11:22 UTC, hsuush requested changes
반환값이 어떻게 되는지도 보여주시고 Notion 작성 및 함수별 swagger 작성해주세요. 밑에 달린 질문도 답해주시면 감사하겠습니다!

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/GptConfig.java
> +}
configuration 관련은 global/config에 작성해주세요

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/NaverObjectStorageConfig.java
> +}
이친구도 위의 코멘트와 같습니다!

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
database상에서 어떻게 반환되는지 보여주시면 좋을 거 같아요. swagger 결과값이 궁금합니다!

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
이건 무슨 API 인지 궁금해요 프론트에서 이걸 직접적으로 사용하고 반환하는 이유가 궁금합니다.

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
저는 swagger를 아직 못봐서 무엇이 반환되는지 모르겠네요. 데이터베이스가 어떤 결과를 주는지 추가해주시면 좋을 거 같습니다. Notion도 업데이트 부탁드려요.

2024-05-08 11:22 UTC, hsuush commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
이 함수 포함 하위 함수들도 swagger 작성 부탁드려요!

2024-05-08 11:39 UTC, hsuush commented
무슨 기능 구현하셨는지도 작성 부탁드려요!

2024-05-10 05:54 UTC, KimChungEon commented on src/main/java/TubeSlice/tubeSlice/domain/text/GptConfig.java
> +}
옮겨놨어용

2024-05-10 05:56 UTC, KimChungEon commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
변환 과정에서 네이버 object storage라는 아마존의 s3 같은 곳을 거쳐가는데 테스트용으로 작성해놓은 거에요.
나중에는 api 하나로 합칠 예정.

2024-05-10 05:56 UTC, KimChungEon commented on src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
> +    }
notion에 작성할게요

2024-05-14 05:50 UTC, hsuush approved these changes
고생하셨습니다!

2024-05-14 05:50 UTC, merged